### ISSUE TITLE
Show Error

### ISSUE THREAD

**Issue by YingHuNLP** [jessevig/bertviz#93] opened 2022-03-24 03:27 UTC
Hello, I can't run the demo, but there is a layer and attention dropdown box, but I can't select the layer, and no figure appears.
![RWHPWWUW7ABZUZ763$)X{PY](https://user-images.githubusercontent.com/49576595/159836142-fb360783-f7b5-4021-abc9-96609afbd4f2.png)

**Comment by guanghuixu** [comment] 2022-03-31 07:59
I'm having the same problem, have you solved it？

**Comment by YingHuNLP** [comment] 2022-03-31 08:53
你好，很抱歉，我依然没有解决这个问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jessevig/bertviz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jessevig/bertviz] Show Error (Issue #93)





 
I'm having the same problem, have you solved it？

**Comment by YingHuNLP** [comment] 2022-03-31 13:49
Hello,&nbsp;
&nbsp; &nbsp; &nbsp;&nbsp;Thank you for your reply.
&nbsp; &nbsp; &nbsp;&nbsp;This is the list of environments I use(1-3). As well as the two simplest examples given on your github for running(4-6).














------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jessevig/bertviz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上7:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jessevig/bertviz] Show Error (Issue #93)





 
Hi @YingHuNLP, thank you for filing the issue and sorry for the delayed response.  Can you tell me which environment you are running this in? Is it vanilla Jupyter Notebook? Also, what version of Python are you using? Have you been able to get any of the code samples to work, e.g. this one?: https://github.com/jessevig/bertviz#sample-code

**Comment by YingHuNLP** [comment] 2022-03-31 23:52
I am so sorry! .
![6](https://user-images.githubusercontent.com/49576595/161167861-1c0b091c-c625-488c-98c5-a96254c34f94.png)
![1](https://user-images.githubusercontent.com/49576595/161167864-7b932b6e-48b4-4ecf-98e9-b612fc709051.png)
![2](https://user-images.githubusercontent.com/49576595/161167866-5180d78b-b46f-416a-afa2-fb974694ed0d.png)
![3](https://user-images.githubusercontent.com/49576595/161167867-f48e5895-3bea-491b-b50b-a480c712316d.png)
![4](https://user-images.githubusercontent.com/49576595/161167870-ebd1eefd-4046-4712-9383-7f1c3d68d167.png)
![5](https://user-images.githubusercontent.com/49576595/161167872-68a2e838-9af3-4457-afd3-33d0c1177118.png)

**Comment by YingHuNLP** [comment] 2022-03-31 23:53
I am so sorry!
![1](https://user-images.githubusercontent.com/49576595/161167931-2de9cabc-7884-4d9d-b0d1-f1f68dfc0d58.png)
![2](https://user-images.githubuse
![3](https://user-images.githubusercontent.com/49576595/161167944-e306fc6c-8236-40b3-87cf-814e35cbd874.png)
rcontent.com/49576595/161167937-9b537538-d6eb-4a13-bb47-b0c87be6a143.png)
![4](https://user-images.githubusercontent.com/49576595/161167955-6ce7d034-67fc-433e-ab45-d7a34592428d.png)
![5](https://user-images.githubusercontent.com/49576595/161167961-c4dd6622-d81f-4d7a-9b63-a48a9846644e.png)
![6](https://user-images.githubusercontent.com/49576595/161167967-277cecf3-1473-4ca8-a775-20169f47132d.png)

**Comment by YingHuNLP** [comment] 2022-03-31 23:54
I am so sorry!
![1](https://user-images.githubusercontent.com/49576595/161168342-b6ca7e6f-a179-4f5c-bf3b-e706f3284989.png)
![2](https://user-images.githubusercontent.com/49576595/161168387-8bcc912a-c7f6-40a4-8472-3ae84c77b4fd.png)
![3](https://user-images.githubusercontent.com/49576595/161168426-fdc2a964-0c56-408d-9b8a-aa0ea6b4ede6.png)
![4](https://user-images.githubusercontent.com/49576595/161168457-4508e213-cc56-4b35-b768-b0a9c050c34b.png)
![5](https://user-images.githubusercontent.com/49576595/161168489-b8419a20-1a96-49bb-9ab0-422fc57e57cd.png)
![6](https://user-images.githubusercontent.com/49576595/161168531-c255b046-e6a7-4436-b30c-0b8a78f98ef4.png)

**Comment by jessevig** [comment] 2022-04-01 00:27
Thanks. In the examples above, it looks like you are using your own local model. Are you able to run the scripts with standard models, e.g. [this one](https://github.com/jessevig/bertviz#sample-code):

from transformers import AutoTokenizer, AutoModel, utils
from bertviz import model_view
utils.logging.set_verbosity_error()  # Suppress standard warnings

model_name = "microsoft/xtremedistil-l12-h384-uncased"  # Find popular HuggingFace models here: https://huggingface.co/models
input_text = "The cat sat on the mat"  
model = AutoModel.from_pretrained(model_name, output_attentions=True)  # Configure model to return attention values
tokenizer = AutoTokenizer.from_pretrained(model_name)
inputs = tokenizer.encode(input_text, return_tensors='pt')  # Tokenize input text
outputs = model(inputs)  # Run model
attention = outputs[-1]  # Retrieve attention from model outputs
tokens = tokenizer.convert_ids_to_tokens(inputs[0])  # Convert input ids to token strings
model_view(attention, tokens)  # Display model view

**Comment by YingHuNLP** [comment] 2022-04-01 01:10
Unfortunately, switching to the standard model still does not work properly.
![image](https://user-images.githubusercontent.com/49576595/161175522-ecc8f25b-a3fd-4e26-a8c5-a14d692ad23f.png)

**Comment by jessevig** [comment] 2022-04-01 12:57
Okay, thanks. To help further debug, could you try running 2 separate cells with each of these commands:

`len(attention)`

`attention[0].shape`

**Comment by jessevig** [comment] 2022-04-01 12:58
Also another cell:

`tokens`

**Comment by YingHuNLP** [comment] 2022-04-02 00:45
Thank you for your help.
model_view is ok. but show is still wrong.
![image](https://user-images.githubusercontent.com/49576595/161357347-ff62e40c-6f5c-45ed-a935-bfc53b88edfd.png)

![image](https://user-images.githubusercontent.com/49576595/161357338-d9ee80cf-dbbf-4df8-bbde-276df121f786.png)

**Comment by jessevig** [comment] 2022-04-02 01:26
Okay, thanks. So one limitation of the neuron view is that you can only have one instance per notebook. Do you get this error condition for the `show` code above when you only have a single cell in your notebook? Also, I didn't see your Python version earlier, can you share it? And is this Chrome browser or something else? Thank you.

**Comment by jessevig** [comment] 2022-04-02 01:27
If you are using Chrome, you could also try View > Developer > Javascript Console to see if there are any Javascript errors for some reason.

**Comment by guanghuixu** [comment] 2022-04-02 01:38
> Thank you for your help. model_view is ok. but show is still wrong. ![image](https://user-images.githubusercontent.com/49576595/161357347-ff62e40c-6f5c-45ed-a935-bfc53b88edfd.png)
> 
> ![image](https://user-images.githubusercontent.com/49576595/161357338-d9ee80cf-dbbf-4df8-bbde-276df121f786.png)

Actually I sucessfully ran it once. But the next time I restart the ```jupyter notebook```, it doesn't work again. Is yours always successful?

**Comment by jessevig** [comment] 2022-04-02 01:39
Yes, it always runs okay on my end.

**Comment by guanghuixu** [comment] 2022-04-02 01:49
> Yes, it always runs okay on my end.

emmm, I find it works again, but I didn't modify any code or setting.

**Comment by jessevig** [comment] 2022-04-02 02:14
Hmm, strange. One thing to try would be to add the following cell prior to the main cell: 

%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

They do this in the Transformers book. I'm not sure if it is necessary, but curious if it helps

**Comment by jessevig** [comment] 2022-04-02 02:16
But in the case when it doesn't work, I think viewing the Javascript console might reveal the issue. In Chrome, this is: View > Developer > Javascript Console

**Comment by guanghuixu** [comment] 2022-04-02 02:44
> Hmm, strange. One thing to try would be to add the following cell prior to the main cell:
> 
> %%javascript require.config({ paths: { d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min', jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min', } });
> 
> They do this in the Transformers book. I'm not sure if it is necessary, but curious if it helps

I may have found a problem that was caused by network instability.
<img width="473" alt="1ec69ac62c9295aef0554f3b1ac17f5" src="https://user-images.githubusercontent.com/20624157/161362797-f9adb26d-f8e3-454c-9ec5-6efefc393317.png">

**Comment by jessevig** [comment] 2022-04-02 03:05
Okay, thanks, that's very helpful. There may be some issue with the d3 dependency too that's causing instability there. There is actually a change in master that changes the d3 import, it's possible that it will resolve this issue, though I'm not sure. 

If you want to run the version in master to see if that helps, you can install from source:

```
git clone https://github.com/jessevig/bertviz.git
cd bertviz
python setup.py develop
```

Thanks for helping debug this!

**Comment by YingHuNLP** [comment] 2022-04-02 04:54
> Okay, thanks. So one limitation of the neuron view is that you can only have one instance per notebook. Do you get this error condition for the `show` code above when you only have a single cell in your notebook? Also, I didn't see your Python version earlier, can you share it? And is this Chrome browser or something else? Thank you.

Thanks. It's ok when only have one instance per notebook. and python=3.9，browser  is Edge.
![image](https://user-images.githubusercontent.com/49576595/161366917-fb24402d-4f34-4bc7-9619-a43d6291a75c.png)

**Comment by jessevig** [comment] 2022-04-02 13:52
Thank you. I've just released a new version that enables multiple neuron view instances per notebook. If you don't mind, please try:

`pip install bertviz==1.4.0`

and let me know if you have any of these issues still. Thanks again!

**Comment by YingHuNLP** [comment] 2022-04-06 00:28
Apologies for the late reply. And thank you for your help.
When using the latest version, everything is OK.

**Comment by jessevig** [comment] 2022-04-06 01:02
Okay, great! Thanks for your help. Closing issue for now, but feel free to re-open if this happens again.

**Closed by jessevig** 2022-04-06 01:02 UTC
