### ISSUE TITLE
I have a problem loading my own model

### ISSUE THREAD

**Issue by WenTingTseng** [jessevig/bertviz#39] opened 2020-02-21 12:02 UTC
Hi，I have a problem loading my own model
 I can successfully load my fine-tune BERT model
But it has a problem message ### TypeError: object of type 'float' has no len() when I call  head_view(attention, tokens)
I don't know how to solve this bug

![擷取](https://user-images.githubusercontent.com/32416416/75033016-dae5ee80-54e4-11ea-8f6e-2feeafad4383.JPG)
Thanks a lot for your help

**Comment by leemengtaiwan** [comment] 2020-02-21 12:14
@WenTingTseng  hi, not sure about the root cause, but have you set the `output_attentions` argument to `True` when loading the pre-trainin model above?

```python
from transformers import BertTokenizer, BertModel
model = BertModel.from_pretrained(model_version, output_attentions=True)
```

**Comment by WenTingTseng** [comment] 2020-02-21 12:28
Hi, leemeng
I was just watching your blog about BERT.Thanks a lot for your help
I solved the problem. It need to set the output_attentions=True in BertConfig
config = bert_config.from_pretrained('C:\\Users\\Acer\\bertviz-master\\bertviz-master\\model2\\config.json',output_attentions=True)
Thanks a lot

**Comment by leemengtaiwan** [comment] 2020-02-21 12:35
Glad to hear that! Keep learning and let’s close the issue.

WenTingTseng <notifications@github.com>於 2020年2月21日 週五，21:28寫道：

**Closed** 2020-02-21 14:48 UTC
